global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ENTERPRISE_SERVICES'
    static_configs:
      - targets:
        - 'LIMSService:80'
        - 'BBMasterService:80'
        # - 'BBMgMtService:80'
        - 'QC:80'
