events {}

http {
    # Upstreams
    upstream lims_service {
        server LIMSService:5000;
    }
    upstream bbmaster_service {
        server BBMasterService:5400;
    }
    upstream bbmgmt_service {
        server BBMgMtService:5402;
    }
    upstream qc_service {
        server QC:5405;
    }

    server {
        listen 80;

        # Serve Angular UI
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Backend APIs
        location /lims/ {
            proxy_pass http://lims_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /bbmaster/ {
            proxy_pass http://bbmaster_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /bbmgmt/ {
            proxy_pass http://bbmgmt_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /qc/ {
            proxy_pass http://qc_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
